[package]
name = "board"
version = "0.1.0"
edition = "2021"

[dependencies]
cli-clipboard = "0.4.0"
ggez = "0.9.3"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.135"
